spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bzhs1992@gmail.com
    password: zqjdwmroqtztbbcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level.org.hibernate.sql=debug
  level.org.hibernate.type.descriptor.sql=trace

kakao:
  apiKey: afd1424272e23370e80792c29e7834c7
  clientId: dcce449896971662a3c6d7ced6e53bed
  secretId: ynq6d6wi8ItcFV4OgfGEFqI7OhwxJZLI
  redirectUrl: http://localhost:8080/kakao/signin

jwt:
  secretKey: backtothefront
  tokenIssuer: queosk

cloud:
  aws:
    credentials:
      access-key: AKIAZFYBURHV3MGMR6EP
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: queosk-bucket