spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level.org.hibernate.sql=debug
  level.org.hibernate.type.descriptor.sql=trace