spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true

logging:
  level.org.hibernate.sql=debug
  level.org.hibernate.type.descriptor.sql=trace

kakaoApiKey: afd1424272e23370e80792c29e7834c7